server:
  port: 9000

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
    sqlScriptEncoding: UTF-8
  messages:
    basename: messages
    encoding: UTF-8
  thymeleaf:
    cache: false

doma:
  dialect: h2
  sql-file-repository: no_cache

fuudoapp:
  album:
    imageDirectory: C:\static\image\